### ISSUE TITLE
remove region specific DNS zones for batch

### ISSUE THREAD

**Issue by utkarshayachit** [mocelj/azbatch-starter-connectivity#3]
There are not needed anymore, AFAICT. https://learn.microsoft.com/en-us/azure/batch/private-connectivity#migration-with-existing-batch-account-private-endpoints.

e.g. `privatelink.eastus.batch.azure.com` need not be created. `privatelink.batch.azure.com` is sufficient.

**Comment by mocelj** [comment]
that's correct - good catch. was an artefact supporting class communication model. This should not be needed moving forward. Will modify the config file.

**Comment by utkarshayachit** [comment]
fix already available in PR #4
