### ISSUE TITLE
add DNS resolver

### ISSUE THREAD

**Issue by utkarshayachit** [mocelj/azbatch-starter-connectivity#5]
We need to add a DNS resolver when VPN gateway is deployed. Without the DNS resolver, using P2S VPN connection is not really useful to access batch and other services that are exposed via private endpoints alone.

ref: https://www.mytechramblings.com/posts/testing-private-dns-resolution-over-a-p2s-vpn-using-azure-dns-private-resolver/

**Comment by mocelj** [comment]
added a dns resolver, when VPN gateway is created. Subnet delegation etc. implemented. To be verified, if a NSG rule etc. is required on this subnet. Was not able to test the automated deployment. Replicated the steps manually in another region but failed to see the  private ip resolution working. Will have to check the vpn client / setup on my local dev box.

**Comment by mocelj** [comment]
tested the dns resolver approach successfully - on client side (in my case Mac OS) the DNS server (either a conditional forwarder for the domains in question, or for all requests) needed to point towards the private IP address of the inbound endpoint of the private dns resolver. Just changing the built-in DNS server from Azure provided to a Custom DNS server did not fix the issue on client side
