### ISSUE TITLE
linux jumbox doesn't have Az CLI  installed

### ISSUE THREAD

**Issue by utkarshayachit** [mocelj/azbatch-starter-connectivity#6]
After logging on to linux jumbox using bastion, `az --version` failed. It should have gotten installed since the init script is setup to install it. Perhaps the init script is not working as expected.

**Comment by mocelj** [comment]
fixed issue - replaced bash script of linux vm configuration with a cloud-init script. Linux VM needs to be deleted before redeploying the resources.

**Comment by mocelj** [comment]
closed issue
